channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.0
  - bioconductor-genomeinfodb
  - bioconductor-genomicranges
  - bioconductor-genomicalignments
  - bioconductor-complexheatmap
  - r-circlize
